[package]
name = "jenda"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
